AWSTemplateFormatVersion: "2010-09-09"

Description: "Create S3 bucket static website with CloudFront distribution"

Parameters:
  DomainName:
    Type: String

  WebSiteDomain:
    Type: String

Resources:
  SSLCertificate:
    Type: AWS::CertificateManager::Certificate
    DependsOn: HostedZone
    Properties:
      DomainName: !Ref WebSiteDomain
      DomainValidationOptions:
        - DomainName: !Ref WebSiteDomain
          HostedZoneId: !Ref HostedZone
      ValidationMethod: DNS

  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: !Ref DomainName
      Name: !Ref WebSiteDomain

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DomainName
      VersioningConfiguration:
        Status: Enabled
      WebsiteConfiguration:
        IndexDocument: index.html

  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Ref DomainName

  s3ReadPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: "s3:GetObject"
            Effect: "Allow"
            Principal:
              CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId
            Resource:
              - !Sub "arn:aws:s3:::${Bucket}/*"

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultRootObject: index.html
        Origins:
          - DomainName: !Sub "${Bucket}.s3.website-${AWS::Region}.amazonaws.com"
            Aliases: !Ref WebSiteDomain
            OriginPath: ""
            Id: myS3Origin
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: "http-only"
        DefaultCacheBehavior:
          Compress: true
          TargetOriginId: myS3Origin
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
        HttpVersion: http2
        ViewerCertificate:
          AcmCertificateArn: !Ref SSLCertificate
          SslSupportMethod: sni-only
        Enabled: true
        IPV6Enabled: true

Outputs:
  outputS3WebsiteURL:
    Value: !GetAtt Bucket.WebsiteURL
    Description: "The S3 bucket static website URL"

  outputS3BucketRegionalName:
    Value: !GetAtt Bucket.RegionalDomainName
    Description: "The S3 bucket's regional domain name"

  outputCertificateArn:
    Description: Issued SSL certificate Arn
    Value: !Ref SSLCertificate

  outputCloudFrontDistributionId:
    Description: CloudFront distribution ID
    Value: !Ref CloudFrontDistribution

  outputCloudFrontDistributionDomainName:
    Description: CloudFront distribution domain name
    Value: !GetAtt CloudFrontDistribution.DomainName

  outputRoute53HostedZoneId:
    Description: Public hosted zone ID
    Value: !GetAtt HostedZone.Id

  outputRoute53HostedZoneNameServers:
    Description: List of name servers for newly created public hosted zone
    Value: !Join [", ", !GetAtt HostedZone.NameServers]
