AWSTemplateFormatVersion: "2010-09-09"

Description: "Create S3 bucket static website with CloudFront distribution"

Parameters:
  DomainName:
    Type: String

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DomainName
      VersioningConfiguration:
        Status: Enabled
      WebsiteConfiguration:
        IndexDocument: index.html

  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Ref DomainName

  s3ReadPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: "s3:GetObject"
            Effect: "Allow"
            Principal:
              CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId
            Resource:
              - !Sub "arn:aws:s3:::${Bucket}/*"

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn: Bucket
    Properties:
      DistributionConfig:
        DefaultRootObject: index.html
        Origins:
          - DomainName: !Sub "${Bucket}.s3.website-${AWS::Region}.amazonaws.com"
            OriginPath: ""
            Id: myS3Origin
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: "http-only"
        DefaultCacheBehavior:
          Compress: true
          TargetOriginId: myS3Origin
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
        HttpVersion: http2
        Enabled: true
        IPV6Enabled: true

Outputs:
  outputS3WebsiteURL:
    Value: !GetAtt Bucket.WebsiteURL
    Description: "The S3 bucket static website URL"

  outputS3BucketRegionalName:
    Value: !GetAtt Bucket.RegionalDomainName
    Description: "The S3 bucket's regional domain name"
