AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  DomainName:
    Type: String

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Ref DomainName
      VersioningConfiguration:
        Status: Enabled
      WebsiteConfiguration:
        IndexDocument: index.html

  s3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: "s3:GetObject"
            Effect: "Allow"
            Principal:
              Service: "cloudfront.amazonaws.com"
            Resource: !Sub "${Bucket.Arn}/*"
            Condition:
              StringEquals:
                "aws:SourceArn": !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}"

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn: Bucket
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt Bucket.DomainName
            OriginPath: /index.html
            Id: myS3Origin
            S3OriginConfig: {}
        DefaultCacheBehavior:
          TargetOriginId: myS3Origin
          AllowedMethods:
            - GET
            - HEAD
            - PUT
            - POST
            - DELETE
            - PATCH
            - OPTIONS
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: false
        Enabled: true
        IPV6Enabled: true
